[package]
name = "humble_port_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.78"
clap = { version = "4.4.11", features = ["derive"] }
ipnet = "2.9.0"
thiserror = "1.0.56"
tokio = { version = "1.7", features = ["full", "tracing"] }
tokio-test = "0.4.3"
